os:
  - linux
  - osx

language: node_js

node_js:
  - stable

before_install:
  - npm install -g xo
  - sudo apt install wine64

install:
  - npm install


script:
  - npm run test

after_success:
  - npm run package-windows
  - npm run semantic-release




